### ISSUE TITLE
access token?

### ISSUE THREAD

**Issue by mikedizon** [laardee/serverless-authentication-facebook#2]
How does one get the access token? It's not immediately obvious

**Comment by laardee** [comment]
Hi, sorry for my late reply, I just noticed this issue. The access token is mapped as `at_hash` in the returned profile (https://github.com/laardee/serverless-authentication/blob/master/src/profile.js). It is set in the Provider class which is used in this provider https://github.com/laardee/serverless-authentication/blob/master/src/provider.js#L85.
